# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  appName: 'exvilearn' 

stages:
- stage: Build
  displayName: Build and Deploy
  jobs:
  - job: Build
    displayName: Build and Deploy
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build Docker image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/DockerFile'
        tags: |
          $(tag)

    - task: Docker@2
      displayName: Login to Docker Hub
      inputs:
        command: login
        containerRegistry: 'Docker Hub'

    - task: Docker@2
      displayName: Push Docker image to Docker Hub
      inputs:
        command: push
        imageName: 'josems135/cursoweb:latest'

    - task: AzureWebApp@1
      displayName: 'Deploy to Azure App Service'
      inputs:
        azureSubscription: 'Azure'
        appName: 'exvilearn-inside'
        containers: 'josems135/cursoweb:latest'
        containerCommand: 'npm run dev'
        enableCustomDeployment: true
        deploymentType: 'dockerContainer'
