trigger:
- '*'

resources:
- repo: self

variables:
  imageName: 'josems135/cursoweb'
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build and Deploy
  jobs:
  - job: Build
    displayName: Build and Deploy
    pool:
      name: 'Exvilearn'
    steps:
    - task: Docker@2
      displayName: Deploy to Azure App Service
      inputs:
        azureSubscription: 'Azure'
        appName: 'exvilearnapp'
        containers: '$(imageName):$(tag)'
        containerCommand: 'npm run dev'
        enableCustomDeployment: true
        deploymentType: 'dockerContainer'
