trigger:
  - '*'

resources:
  - repo: self

variables:
  imageName: 'josems135/cursoweb'
  tag: 'latest'

stages:
  - stage: Build
    displayName: Build and Deploy
    jobs:
      - job: Build
        displayName: Build and Deploy
        pool:
          vmImage: 'ubuntu-20.04' 
        steps:
          - task: Docker@2
            displayName: Build Docker image
            inputs:
              command: 'buildAndPush'
              containerRegistry: 'Docker Hub'
              repository: '$(imageName)'
              tags: '$(tag)'

          - task: Docker@2
            displayName: Deploy to Azure App Service
            inputs:
              azureSubscription: 'Azure'
              appName: 'exvilearnapp'
              containers: '$(imageName):$(tag)'
              containerCommand: 'npm run dev'
              enableCustomDeployment: true
              deploymentType: 'dockerContainer'

          - task: AzureCLI@2
            displayName: 'Restart Azure App Service'
            inputs:
              azureSubscription: 'Azure'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: 'az webapp restart --name exvilearnapp --resource-group Exvilearninfra'
